Press Enter to start the looping search...
==================================20180511_15:33:35 - =============================


we dont have flights available 


==================================END=============================


==================================20180511_15:33:59 - =============================


we dont have flights available 


==================================END=============================


==================================20180511_15:34:04 - =============================


we got available flights 

[{'status': u'4 LEFTBusiness ClassAvailable', 'flight': u' CX0872', 'time': u'00:30 24 MayHKGHong Kong'}]



==================================END=============================


==================================20180511_15:34:10 - =============================


we got available flights 

[{'status': u'Business ClassAvailable', 'flight': u' CX0872', 'time': u'00:30 23 MayHKGHong Kong'}, {'status': u'4 LEFTBusiness ClassAvailable', 'flight': u' CX0892', 'time': u'18:55 23 MayHKGHong Kong'}]



==================================END=============================

Traceback (most recent call last):
  File "queryBA.py", line 246, in <module>
    loopForTicket(browser)
  File "queryBA.py", line 229, in loopForTicket
    navigateThroughDays(browser, 3)
  File "queryBA.py", line 214, in navigateThroughDays
    WebDriverWait(browser, 30).until(EC.presence_of_element_located((By.XPATH, tabListPath)))
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 63, in __call__
    return _find_element(driver, self.locator)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 401, in _find_element
    raise e
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.4 x86_64)

Tue May 08 09:59:30 2018
we are past set time, fire immediately
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
error now
we re try it
we did not find the wanted button Message: 

Traceback (most recent call last):
  File "firstComeFirstGet.py", line 121, in <module>
    if getPage(browser):
  File "firstComeFirstGet.py", line 81, in getPage
    browser.refresh()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 815, in refresh
    self.execute(Command.REFRESH)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.4 x86_64)

